### ISSUE TITLE
Criar parâmetro que permita incluir subtags de uma tag especificada no xpath

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/Xml2Isis#4]
Dado um arquivo xml:

&lt;abstract&gt;&lt;b&gt;Background:&lt;/b&gt; protein&lt;/abstract&gt;

O comportamento padrão de uma especificação xpath "/abstract" deve retornar " protein" mas se um parâmetro de chamada for ativado então o mesmo xpath deverá retornar "&lt;b&gt;Background:&lt;/b&gt; protein"

**Comment by heitorbarbieri** [comment]
@botturam  favor acrescentar o parâmetro "--allowSubElements" no shell Xml2Isis.sh ou nos lugares onde exista a chamada: 

java -Xms512m -Xmx2g -cp /usr/local/bireme/java/Xml2Isis/dist/Xml2Isis.jar:/usr/local/bireme/java/Xml2Isis/dist/lib/Bruma.jar:/usr/local/bireme/java/Xml2Isis/dist/lib/Utils.jar br.bireme.xml2isis.Xml2Isis $1 $2 $3 $4 $5 $6 $7 $8 $9

Depois, por favor, testar se o problema foi solucionado.

Obrigado

**Comment by botturam** [comment]
foi testado e validado:

Exemplor PMID: 30079259
370  "This paper presents a convenient and sensitive LC-MS/MS method for the simultaneous determination of carbadox and olaquindox residues, including desoxyolaquindox (DOLQ), desoxycarbadox (DCBX), quinoxaline-2-carboxylic acid (QCA), 3-methyl-quinoxaline-2-carboxylic acid (MQCA), and the glycine conjugates of QCA and MQCA (namely, QCA-glycine and MQCA-glycine, resp.) in swine muscle and liver tissues. Tissue samples were extracted with 2% metaphosphoric acid in 20% methanol and cleaned up by solid-phase extraction (SPE) on a mixed-mode anion-exchange column (Oasis MAX). Analysis was performed on a C column by detection with mass spectrometry in the multiple reaction monitoring (MRM) mode. The limits of detection (LODs) of the six analytes were determined to be 0.01 g·kg to 0.25 g·kg, and the limits of quantification (LOQs) were 0.02 g·kg to 0.5 g·kg. The total recoveries of the six analytes in all tissues were higher than 79.1% with the RSD% less than 9.2%. The developed method can determine the real residue level of QCA and MQCA, whether they are present in free form or as glycine conjugates in tissues, together with the carcinogenic desoxy metabolites DCBX and DOLQ with high recovery. Therefore, this method was suitable for routine analysis of residue control programmes and the residue depletion study of CBX and OLQ on swine."

370  "This paper presents a convenient and sensitive LC-MS/MS method for the simultaneous determination of carbadox and olaquindox residues, including desoxyolaquindox (DOLQ), desoxycarbadox (DCBX), quinoxaline-2-carboxylic acid (QCA), 3-methyl-quinoxaline-2-carboxylic acid (MQCA), and the glycine conjugates of QCA and MQCA (namely, QCA-glycine and MQCA-glycine, resp.) in swine muscle and liver tissues. Tissue samples were extracted with 2% metaphosphoric acid in 20% methanol and cleaned up by solid-phase extraction (SPE) on a mixed-mode anion-exchange column (Oasis MAX). Analysis was performed on a C18 column by detection with mass spectrometry in the multiple reaction monitoring (MRM) mode. The limits of detection (LODs) of the six analytes were determined to be 0.01 µg·kg-1 to 0.25 µg·kg-1, and the limits of quantification (LOQs) were 0.02 µg·kg-1 to 0.5 µg·kg-1. The total recoveries of the six analytes in all tissues were higher than 79.1% with the RSD% less than 9.2%. The developed method can determine the real residue level of QCA and MQCA, whether they are present in free form or as glycine conjugates in tissues, together with the carcinogenic desoxy metabolites DCBX and DOLQ with high recovery. Therefore, this method was suitable for routine analysis of residue control programmes and the residue depletion study of CBX and OLQ on swine."
